// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "tech-test/internal/article/entity"

	mock "github.com/stretchr/testify/mock"
)

// ArticleRepository is an autogenerated mock type for the ArticleRepository type
type ArticleRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *ArticleRepository) Get(_a0 string, _a1 int, _a2 int, _a3 int) ([]entity.Article, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 []entity.Article
	if rf, ok := ret.Get(0).(func(string, int, int, int) []entity.Article); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Article)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int, int, int) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: _a0
func (_m *ArticleRepository) Store(_a0 entity.Article) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Article) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewArticleRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewArticleRepository creates a new instance of ArticleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewArticleRepository(t mockConstructorTestingTNewArticleRepository) *ArticleRepository {
	mock := &ArticleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
