// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AuthorUsecase is an autogenerated mock type for the AuthorUsecase type
type AuthorUsecase struct {
	mock.Mock
}

// register provides a mock function with given fields:
func (_m *AuthorUsecase) register() {
	_m.Called()
}

type mockConstructorTestingTNewAuthorUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthorUsecase creates a new instance of AuthorUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthorUsecase(t mockConstructorTestingTNewAuthorUsecase) *AuthorUsecase {
	mock := &AuthorUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
